### ISSUE TITLE
code fragments have incorrect quotes for python

### ISSUE THREAD

**Issue by d-c-d** [kevinmcaleer/kevsrobots.com#11]
'''
a = 65
b = 42
c = 180 - a + b 
print(‘the missing angle is: ‘,c)
'''
[Example 2](https://beta.kevsrobots.com/learn/micropython/09_example02.html)

when cutting and pasting the code into the repl - the quotes

<html>
<body>

Character | ‘
-- | --
Character name | LEFT SINGLE QUOTATION MARK

</body>
</html>

<html>
<body>

Hex code point | 2018
-- | --
Decimal code point | 8216

</body>
</html>

**Comment by kevinmcaleer** [comment]
Thanks - I think I typed this one into the Notes app on my phone and then cut and pasted it into Visual Studio Code. Fixed, and will show correctly in the next build. Thanks
